### ISSUE TITLE
Error generating models

### ISSUE THREAD

**Issue by JoseSputnik** [contentstack/contentstack-model-generator#12]
Hi,
I'm trying to generate the models for my Stack but it's failing. I've made sure that the stack api and the authtoken are correct but it fails anyway.
I'm using version 0.4.0.

Please, could you help me out?

Thank you.

![image](https://user-images.githubusercontent.com/86773114/124627388-cb6c0900-de7f-11eb-9c0f-16eb389a7882.png)

**Comment by JoseSputnik** [comment]
I'm debugging the code in my laptop. It fails in line 201 in ContentstackClient.cs.
This is the exception message "The remote server returned an error: (422) Unprocessable Entity."

**Comment by uttamukkoji** [comment]
Hi @JoseSputnik,

Thanks for raising the issue. Can you please confirm following:
- API key for the Stack is proper
- Auth token for the user is valid
- User have access to the Stack
- Host for the Stack you want to generate Models i.e. for NA region host is `api.contentstack.io` (this is default) and for EU region host is `eu-api.contentstack.com`

**Comment by JoseSputnik** [comment]
Hi uttamukkoji,
thank you for your rapid response!

- API key for the Stack is proper => Confirmed!
- Auth token for the user is valid => Confirmed!
- User have access to the Stack => Confirmed!
- Host for the Stack you want to generate Models i.e. for NA region host is api.contentstack.io (this is default) and for EU region host is eu-api.contentstack.com => My Stack is EU region but I'm not providing any parameter to set the region as there is no such parameter, at least I couldn't find that in the doc. How can I set the region to EU??

Cheers.

**Comment by uttamukkoji** [comment]
Hi @JoseSputnik ,

Following is example to pass host using short key `-e`:

`contentstack.model.generator -a <stack_api_key> -A <authtoken> -e eu-api.contentstack.com`

**Comment by JoseSputnik** [comment]
Thank you, uttamukkoji, it works!
I didn't realise we had that parameter.

Regards.
